// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxjaCZo6PlRsOD9D1Zw7roGTiUo1ggZgM',
    appId: '1:465262338358:web:d1d2d311cfd87a5af65397',
    messagingSenderId: '465262338358',
    projectId: 'urubank-62c0a',
    authDomain: 'urubank-62c0a.firebaseapp.com',
    databaseURL: 'https://urubank-62c0a-default-rtdb.firebaseio.com',
    storageBucket: 'urubank-62c0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARFZyQzLxnodQiyXbftiF7fZSRtq4uYL4',
    appId: '1:465262338358:android:f92d11a242837c5af65397',
    messagingSenderId: '465262338358',
    projectId: 'urubank-62c0a',
    databaseURL: 'https://urubank-62c0a-default-rtdb.firebaseio.com',
    storageBucket: 'urubank-62c0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqagtt0OGCJfcf58CRW977hlYvJ6YGjMQ',
    appId: '1:465262338358:ios:94790b837d140638f65397',
    messagingSenderId: '465262338358',
    projectId: 'urubank-62c0a',
    databaseURL: 'https://urubank-62c0a-default-rtdb.firebaseio.com',
    storageBucket: 'urubank-62c0a.appspot.com',
    iosClientId: '465262338358-c1u2r01bgnkgutgi0uvbpdbtacavuu3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.uruBank',
  );
}
